<a href="https://colab.research.google.com/github/mark-protik/mark-protik/blob/main/micro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Micro Project**  

#**Load data**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/dataSet.csv')
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

##**Data preparation**


In [257]:
if df.isnull().sum().any():
    df = df.dropna()

###data separation as X and Y

In [258]:
y = df['label']
y

0         rice
1         rice
2         rice
3         rice
4         rice
         ...  
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [259]:
x = df.drop('label',axis=1)
x

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

##**Split the dataSet**

###Spliting for test and training

In [260]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=100)

In [261]:
x_train

N    P    K  temperature   humidity        ph    rainfall
1960  131   60   17    25.320237  81.794759  7.425041   83.465325
427     9   66   21    30.118121  34.133078  5.719890  157.085823
1148   38   15   27    33.746269  48.503876  6.777788   92.264392
472     5   68   20    18.729877  61.331862  5.001039  139.871004
185    88   38   15    25.082397  65.921958  6.455117   62.491908
...   ...  ...  ...          ...        ...       ...         ...
350    11   72   20    19.522262  24.926072  5.951177  113.334026
1930  118   45   23    23.370444  77.431989  7.977651   71.678707
79     81   41   38    22.678461  83.728744  7.524080  200.913316
1859   37   10   32    28.963183  95.163337  6.165085  222.803013
1544    2  123  205    22.366293  90.785725  5.739652  124.983162

[1760 rows x 7 columns]

In [262]:
x_test

N   P   K  temperature   humidity        ph    rainfall
1743   59  62  52    43.675493  93.108872  6.608668  103.823566
1777   52  51  53    38.382315  93.103786  6.985804  210.273535
972    18  21  35    23.280123  94.943305  6.368561  111.138210
1958  116  52  19    22.942767  75.371706  6.114526   67.080226
2058   89  57  43    26.915150  73.198975  6.998787  177.223305
...   ...  ..  ..          ...        ...       ...         ...
1359   81   6  55    24.889105  85.870591  6.110143   51.706991
287    37  55  82    19.455918  18.022359  8.423874   78.449106
19     88  35  40    23.579436  83.587603  5.853932  291.298662
1656   17  16  14    16.396243  92.181519  6.625539  102.944161
1314  104  17  46    25.713143  80.229728  6.190016   43.089618

[440 rows x 7 columns]

#**Model Build**

###Some pre processing

In [263]:
from sklearn.preprocessing import LabelEncoder,StandardScaler


le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

#Model like KNN and Logistic regression
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)


##***Logistic Regression***


In [264]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, random_state=100)
lr.fit(X_train_scaled, y_train_encoded)

LogisticRegression(max_iter=1000, random_state=100)

### **Apply the model to make prediction**

In [265]:
y_lr_train_pred = lr.predict(X_train_scaled)
y_lr_test_pred = lr.predict(X_test_scaled)

In [266]:
y_lr_train_pred

array([ 6, 18, 12, ...,  8,  4,  0])

In [267]:
y_lr_test_pred

array([17, 17, 19,  6,  8, 11, 15, 20, 14,  9,  1, 19, 17, 12,  5, 18, 18,
        6, 17, 10,  4,  6, 12, 12, 14,  6,  0, 15, 10, 13,  6,  5, 18, 12,
        1, 15,  6, 17, 21,  9,  8, 10, 11, 17,  0,  2, 11,  6, 13, 18,  7,
        9, 13,  9, 13, 16,  8, 16,  9,  1, 11,  2, 11,  7, 10, 19,  9,  7,
       16,  9, 19,  7,  8, 21,  2,  9,  8,  5, 14,  7,  6,  0,  9,  0, 15,
       19, 14,  5,  2,  6, 16,  8,  6, 19, 12,  0, 11,  6, 12,  7, 19,  6,
        5,  0,  2, 11, 19, 13,  1,  9, 10,  0,  4,  4, 12, 10,  3, 13, 14,
       11, 12,  4,  2,  5, 16,  8,  3, 14, 10, 21,  4,  0, 17, 20,  1,  7,
        7, 17, 17, 20,  1,  9,  5, 15, 11, 20, 19, 19,  7,  0, 15, 15, 17,
        4,  3,  1,  8, 21, 16, 17, 17,  3,  1,  5, 19,  3, 10,  8, 13,  9,
        4,  9, 20,  3,  6,  1, 13, 12, 14,  4,  7, 10, 18,  5, 10,  6, 10,
        8,  3, 20, 15,  0, 13,  1,  5,  3,  9,  3, 16,  9, 18, 11, 16,  6,
        6,  3,  7,  1, 15, 15,  1,  8, 20,  2, 13, 19,  5, 20, 16, 16, 13,
       12,  4,  3, 12, 11

In [268]:
y_train_encoded

array([ 6, 18, 12, ..., 20,  4,  0])

In [269]:

y_pred_int = y_lr_train_pred.round().astype(int)


y_pred_labels = le.inverse_transform(y_pred_int)
y_pred_labels


array(['cotton', 'pigeonpeas', 'mango', ..., 'jute', 'coconut', 'apple'],
      dtype=object)

###**Evaluate the model**

In [270]:
print("Logistic Regression Accuracy:", accuracy_score(y_test_encoded, y_lr_test_pred))

Logistic Regression Accuracy: 0.9681818181818181


###**Classification report**

In [271]:
print("\nClassification Report:\n", classification_report(y_test_encoded, y_lr_test_pred, target_names=le.classes_))


Classification Report:
               precision    recall  f1-score   support

       apple       1.00      1.00      1.00        18
      banana       1.00      1.00      1.00        21
   blackgram       1.00      0.91      0.95        22
    chickpea       1.00      1.00      1.00        25
     coconut       0.96      1.00      0.98        24
      coffee       1.00      1.00      1.00        23
      cotton       1.00      0.96      0.98        26
      grapes       1.00      1.00      1.00        20
        jute       1.00      0.96      0.98        23
 kidneybeans       0.95      0.95      0.95        20
      lentil       0.86      0.90      0.88        21
       maize       0.95      1.00      0.98        20
       mango       1.00      1.00      1.00        20
   mothbeans       0.89      0.89      0.89        19
    mungbean       0.87      1.00      0.93        13
   muskmelon       0.94      1.00      0.97        15
      orange       1.00      0.95      0.97        20
  

###**Confusion matrix**

In [272]:

print("\nConfusion Matrix:\n", confusion_matrix(y_test_encoded, y_lr_test_pred))


Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 25  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 19  0  0  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 17  0  0  0  0  1  0  0  0]
 [ 0  0  0  0 

##**Pre processing**

In [273]:
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)


##***Random Forest***

In [292]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

x_train_array = x_train.values
rf = RandomForestClassifier(
    n_estimators=100,       # number of trees
    max_depth=None,         # let trees expand until all leaves are pure
    random_state=100,
    n_jobs=-1               # use all CPU cores
)
rf.fit(x_train_array, y_train_enc)

y_pred_enc = rf.predict(x_test.values)

y_pred = le.inverse_transform(y_pred_enc)

###**Evaluate the model**

In [295]:
print("\nRandom Forest Accuracy:", accuracy_score(y_test_enc, y_pred_enc))


Random Forest Accuracy: 0.9977272727272727


###**Classificaton Report**

In [296]:
print("\nClassification Report:\n", classification_report(y_test_enc, y_pred_enc, target_names=le.classes_))


Classification Report:
               precision    recall  f1-score   support

       apple       1.00      1.00      1.00        18
      banana       1.00      1.00      1.00        21
   blackgram       1.00      0.95      0.98        22
    chickpea       1.00      1.00      1.00        25
     coconut       1.00      1.00      1.00        24
      coffee       1.00      1.00      1.00        23
      cotton       1.00      1.00      1.00        26
      grapes       1.00      1.00      1.00        20
        jute       1.00      1.00      1.00        23
 kidneybeans       1.00      1.00      1.00        20
      lentil       1.00      1.00      1.00        21
       maize       0.95      1.00      0.98        20
       mango       1.00      1.00      1.00        20
   mothbeans       1.00      1.00      1.00        19
    mungbean       1.00      1.00      1.00        13
   muskmelon       1.00      1.00      1.00        15
      orange       1.00      1.00      1.00        20
  

###**Confusion matrix**

In [297]:
print("\nConfusion Matrix:\n", confusion_matrix(y_test_enc, y_pred_enc))


Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 21  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 

##***DecisionTreeClassifier***

In [298]:
from sklearn.tree import DecisionTreeClassifier


dt = DecisionTreeClassifier(
    criterion='gini',
    max_depth=None,         # expand until all leaves are pure
    random_state=100
)
dt.fit(x_train_array, y_train_enc)

y_pred_enc = dt.predict(x_test.values)

y_pred = le.inverse_transform(y_pred_enc)

###**Evaluate the model**

In [299]:
print("Accuracy:", accuracy_score(y_test_enc, y_pred_enc))

Accuracy: 0.990909090909091


###**Classification report**

In [300]:
print("\nClassification Report:\n", classification_report(y_test_enc, y_pred_enc))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        21
           2       1.00      0.95      0.98        22
           3       1.00      1.00      1.00        25
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00        23
           6       1.00      1.00      1.00        26
           7       1.00      1.00      1.00        20
           8       1.00      0.96      0.98        23
           9       1.00      1.00      1.00        20
          10       1.00      1.00      1.00        21
          11       0.95      0.90      0.92        20
          12       1.00      1.00      1.00        20
          13       1.00      1.00      1.00        19
          14       1.00      1.00      1.00        13
          15       1.00      1.00      1.00        15
          16       1.00      1.00      1.00        20
  

###**Confusion matrix**

In [301]:
print("\nConfusion Matrix:\n", confusion_matrix(y_test_enc, y_pred_enc))


Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 21  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 

##***KNN***

In [283]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(
    n_neighbors=5,         # Number of neighbors to use
    metric='minkowski',    # Distance metric (default is Euclidean)
    p=2                    # p=2 for Euclidean, p=1 for Manhattan
)
knn.fit(X_train_scaled, y_train_enc)

y_pred_enc = knn.predict(X_test_scaled)

y_pred = le.inverse_transform(y_pred_enc)

###**Evaluate the model**

In [284]:
print("Accuracy:", accuracy_score(y_test_enc, y_pred_enc))

Accuracy: 0.9818181818181818


###**Classification report**

In [285]:
print("\nClassification Report:\n", classification_report(y_test_enc, y_pred_enc))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        21
           2       0.96      1.00      0.98        22
           3       1.00      1.00      1.00        25
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00        23
           6       1.00      1.00      1.00        26
           7       1.00      1.00      1.00        20
           8       0.96      1.00      0.98        23
           9       1.00      1.00      1.00        20
          10       0.87      0.95      0.91        21
          11       1.00      1.00      1.00        20
          12       1.00      1.00      1.00        20
          13       0.94      0.89      0.92        19
          14       1.00      1.00      1.00        13
          15       1.00      1.00      1.00        15
          16       1.00      0.90      0.95        20
  

###**Confusion matrix**





In [286]:
print("\nConfusion Matrix:\n", confusion_matrix(y_test_enc, y_pred_enc))


Confusion Matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0 17  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 

#**Best model**

In [302]:
models = {
    'Logistic Regression': lr,
    'Random Forest': rf,
    'Decision Tree': dt,
    'KNN': knn
}

# Determine the best model based on accuracy
best_model_name = max(models, key=lambda k: accuracy_score(y_test_enc, models[k].predict(X_test_scaled if k in ['Logistic Regression', 'KNN'] else x_test.values)))
best_model = models[best_model_name]
print(f"\nThe best-performing model is: {best_model_name}")


The best-performing model is: Random Forest


#**Predict crops**

In [288]:
import ipywidgets as widgets
from IPython.display import display
from sklearn.preprocessing import StandardScaler

In [303]:
# Create input widgets for each feature
feature_names = x.columns
input_widgets = {feature: widgets.FloatText(description=f"{feature}:") for feature in feature_names}

# Create predict button and output area
predict_button = widgets.Button(description='Predict Crop')
output = widgets.Output()

# Define prediction function
def predict_crop(button):
    with output:
        output.clear_output()
        # Collect input values
        features = [input_widgets[feature].value for feature in feature_names]
        features_array = np.array([features])
        # Scale features if necessary
        if best_model_name in ['Logistic Regression', 'KNN']:
            features_scaled = scaler.transform(features_array)
            prediction_enc = best_model.predict(features_scaled)[0]
        else:
            prediction_enc = best_model.predict(features_array)[0]
        # Decode the prediction
        prediction = le.inverse_transform([prediction_enc])[0]
        print(f"The recommended crop is: {prediction}")

# Attach the prediction function to the button
predict_button.on_click(predict_crop)

# Display the interface
print("\nEnter the values below to predict the recommended crop:")
display(widgets.VBox(list(input_widgets.values()) + [predict_button, output]))


Enter the values below to predict the recommended crop:
